# Application
spring.application.name=${SPRING_APPLICATION_NAME:rural-backend}
server.port=${SERVER_PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rural-res}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.aogdev.rural=${LOGGING_LEVEL_APP:DEBUG}
logging.level.org.springframework.web=${LOGGING_LEVEL_WEB:DEBUG}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_SQL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_LEVEL_BINDER:TRACE}

# Security - dev
spring.security.user.name=${SECURITY_USER_NAME:admin}
spring.security.user.password=${SECURITY_USER_PASSWORD:admin}
